### ISSUE TITLE
incremental sync not robust enough to handle null values in updated_at

### ISSUE THREAD

**Issue by aroder** [edgarrmondragon/tap-jotform#139]
The jotform API consistently provides an `updated_at` field. However, for submissions, the initial value of this property is `null`.

That means queries used by the incremental syncing, such as `{{urlBase}}/form/231005246607144/submissions?filter={"updated_at:gt":"2022-04-21 19:25:37"}` exclude newly created submissions

**Comment by edgarrmondragon** [comment]
@aroder would this be solved by simply making the submissions stream perform full table replication by default?
